#!/usr/bin/env ansible-playbook
---
- name: deploy swift nodes
  hosts: storage
  sudo: True
  vars_files:
    - "global_vars.yml"
  roles:
    - {role: pre_config, when: "{{ configure_gerrit }}" }
    - swift
    - {role: swiftonfile, when: "{{ configure_swiftonfile }}" }
    - post_config

- name: deploy benchmark nodes
  hosts: benchmark
  sudo: True
  vars_files:
    - "global_vars.yml"
  roles:
    - ssbench

- name: run benchmark
  hosts: benchmark
  tags: run_benchmark
  vars_files:
    - "global_vars.yml"
  roles:
    - run_benchmark

- name: retrieve result
  hosts: all
  tags: retrieve_result
  vars_files:
    - "global_vars.yml"
  roles:
    - retrieve_result

- name: common tools
  hosts: all
  sudo: True
  tags: tools
  vars_files:
    - "global_vars.yml"
  tasks:
    - name: Install tools
      apt: pkg={{item}} state=installed update-cache=yes 
      with_items:
        - iperf

- name: start bandwith test (storage)
  hosts: storage
  tags: bandwidth
  vars_files:
    - "global_vars.yml"
  vars:
    server: true
    up: true
  roles:
    - check_bandwidth

- name: check bandwith (benchmark)
  hosts: benchmark
  tags: bandwidth
  vars_files:
    - "global_vars.yml"
  vars:
    server: false

  roles:
    - check_bandwidth

- name: stop bandwith test (storage)
  hosts: storage
  tags: bandwidth
  vars_files:
    - "global_vars.yml"
  vars:
    server: true
    up: false
  roles:
    - check_bandwidth


