---

- shell: df
  register: df_ret
  when: inventory_hostname in groups['storage']

- name: show disk usage
  local_action: command echo item
  with_items: df_ret.stdout
  when: inventory_hostname in groups['storage']

- name: Fetch ssbench result
  sudo: yes
  fetch: >
      src=/tmp/{{user}}-{{key}}-{{item}}.csv
      dest=result/result-{{item}}.csv
      flat=yes
  with_items:
    - "{{concurrency}}"
  when: inventory_hostname in groups['benchmark']
